name: 'learn-fabric'

x-ubuntu: &ubuntu
  build:
    context: docker/ubuntu
  volumes:
    - ./ssh:/ssh
  environment:
    SSH_USERNAME: 'vagrant'
    SSH_PASSWORD: 'vagrant'
  hostname: ubuntu
  ports:
    - '2201:22'
  networks:
    - net

services:
  control:
    build:
      context: docker/control
    volumes:
      - ./fabric:/fabric
      - ./ssh:/ssh
    working_dir: /fabric
    hostname: control
    networks:
      - net
  ubuntu-1:
    <<: *ubuntu
    hostname: ubuntu-1
    ports:
      - '2201:22'
  ubuntu-2:
    <<: *ubuntu
    hostname: ubuntu-2
    ports:
      - '2202:22'

networks:
  net:
    driver: bridge
